# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='date_of_jounery',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='passenger_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
